### ISSUE TITLE
Elements to include in ISO document model

### ISSUE THREAD

**Issue by opoudjis** [riboseinc/asciidoctor-iso#1]
The gem now includes all elements necessary to render the Rice example document. But of course your interest is in IT standards, and there are elements of Asciidoc that the document model does not yet include. Which of the following should be added?

* Audio
* Video
* Page Breaks
* Horizontal Rules ("Thematic Breaks")
* Preformatted ("Literal")
* Sourcecode ("Listing")
* Callouts and Callout numbers (for sourcecode)
* Quotes
* Verse
* Sidebars
* Examples (except as container of images = figures)
* Definition lists (except when embedded in formulas and figures as keys)

**Comment by ronaldtse** [comment]
We should disable these:

* Audio / Video

We will need:

* Sourcecode (as `<code>`?)
* Page break (as `<pagebreak>`?)
* Callouts and callout line numbers
* Quotes
* Definitions (see separate issue)

The rest we can hold on for now until the need arises.

**Comment by opoudjis** [comment]
Definitions, Pagebreak added.

**Comment by opoudjis** [comment]
Added the remainder (though not yet tested). Keeping ticket open.

**Comment by opoudjis** [comment]
The only features not added are:

* Audio
* Video
* Page Breaks (added to code but not to document model)
* Horizontal Rules ("Thematic Breaks")
* Preformatted ("Literal")
* Verse
* Sidebars (used instead as reviewer notes)
* Examples (except as container of images = figures)
