### ISSUE TITLE
Generate HTML and PDF output

### ISSUE THREAD

**Issue by opoudjis** [riboseinc/asciidoctor-iso#10]
For pasting into ISO Word template, or at least to generate a Word document for ISO consumption. Default pathway would be ISO XML to HTML via XSLT.

1. AsciiDoc -> ISO-XML (the format we're doing) -> HTML / PDF

**Comment by ronaldtse** [comment]
Agree with the path too!

**Comment by opoudjis** [comment]
The path has changed; #9 is generating Word HTML. This ticket will map Word HTML into display HTML and/or PDF where necessary; that mapping should be minimal.

**Comment by opoudjis** [comment]
These will be separate classes (likely separate gems) inheriting from the Word converter

**Comment by opoudjis** [comment]
HTML is now being generated by isodoc.

**Comment by ronaldtse** [comment]
HTML output from `isodoc` is very nice -- and I think we should move all isodoc xml processing to the `isodoc` gem too 😉  See https://github.com/riboseinc/isodoc/issues/7

**Comment by opoudjis** [comment]
@ronaldtse to investigate whether unoconv based solution for PDF will work locally.

**Comment by ronaldtse** [comment]
@opoudjis so unoconv only works with LibreOffice 4.x out of box. `brew`'s default is 6.x so it outputs this message:

```
unoconv: Cannot find a suitable pyuno library and python binary combination in /Applications/LibreOffice.app/Contents
ERROR: No module named uno

unoconv: Cannot find a suitable office installation on your system.
ERROR: Please locate your office installation and send your feedback to:
       http://github.com/dagwieers/unoconv/issues
```

As detailed here, https://github.com/dagwieers/unoconv/issues/417, there is no solution unless you downgrade to 4.x.

**Comment by ronaldtse** [comment]
Honestly its probably easiest to do PDF directly.

**Comment by opoudjis** [comment]
So we're closing this?

**Comment by ronaldtse** [comment]
Yes, we should produce html and word output from `isodoc` instead of this gem.
