### ISSUE TITLE
Method to specify dash in title?

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-iso#112]
Some ISO Standards have a seemingly 4-part title, where 2 parts are set in the main title element.

However, none of `&#x2014;` or `&mdash;` work. Both just display verbatim in the resulting Word doc.

Thoughts?

**Comment by opoudjis** [comment]
Yes, this is the Asciidoc document header, which is very intolerant of any markup: anything in there passes straight through as is. The only way to get a non-Ascii character in there is to enter it as raw Unicode, not as an entity. So for dash, you have to enter option-shift-hyphen on the Mac:

Standard—Subtandard.

I'll document.
