### ISSUE TITLE
`[example]` should not render with outer border

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-iso#113]
Examples should be shown just like a note:

![screen shot 2018-03-02 at 12 53 54 am](https://user-images.githubusercontent.com/11865/36857891-a3aaa64a-1db4-11e8-93b0-ac6cab017472.png)

**Comment by opoudjis** [comment]
... The examples in ISO/IEC DIR 2 were all boxed. And this isn't just like a Note: it's hanging indent. (Unless notes are hanging indents as well?)

ISO/IEC DIR 2 does not actually say much about formatting -- and neither does the presupplied format. Will action these, but would be more comfortable if there was in fact an explicit format spec.

**Comment by ronaldtse** [comment]
Yes I know — DIR 2 has them boxed. But DIR 1 has them open. So weird.

**Comment by ronaldtse** [comment]
Or I thought, DIR 2 examples are actually boxed figures with an example inside.

**Comment by opoudjis** [comment]
I defer to your example from ISO 690. Fixed in isodoc.
