### ISSUE TITLE
Wrong rendering of references

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-iso#114]
Previously, in T&D I could do this:

```
=== myterm
mydef

[.source]
<<ISO27000>>, 3, updated Note
```

The source line will render as:
```
[SOURCE: ISO/IEC 27001, 3, modified -- updated Note]
```

But now, the source line has changed to this:
```
[.source]
<<ISO27000,clause 3>>, updated Note
```

And it renders this:

The source line will render as:
```
[SOURCE: ISO/IEC 27001, Clause 3, modified -- updated Note]
```

And this is wrong -- according to Part 2, "3.2" should just be referred as "3.2", while "3" should be "Clause 3".

**Comment by opoudjis** [comment]
Ugh, ISO's idiosyncratic handling of subclause references. OK, will make an exception for ISO/IEC locality referencing.

**Comment by opoudjis** [comment]
Fixed in Isodoc. I apply the distinction between "Clause 3" and "3.1", but only to clauses, not other localities.
