### ISSUE TITLE
ISO ordered lists are only alpha

### ISSUE THREAD

**Issue by opoudjis** [riboseinc/asciidoctor-iso#117]
Hence the convention in https://github.com/riboseinc/isodoc/issues/30. Will fix CSS ordered list style, and will set default to loweralpha. @ronaldtse , we probably should not allow users to override loweralpha.

**Comment by opoudjis** [comment]
Need to enforce a) 1) i) A) I) in HTML output. Brackets already in place in Word thanks to Word stylesheet change.

**Comment by opoudjis** [comment]
Done

**Comment by opoudjis** [comment]
You mean embed in the grammar? The way to do it is to actually suppress the @type attribute on ordered lists for ISO.

**Comment by ronaldtse** [comment]
I meant to spec this in asciidoctor-iso so that the Word output will use these list item styles?

**Comment by opoudjis** [comment]
Already done, it's happening on the call to Html2doc
