### ISSUE TITLE
Critical error: List items a) keep increasing within the document without restarting

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-iso#119]
List 1 goes from a) to e), then List 2 should restart from a) but starts with f), etc.

**Comment by opoudjis** [comment]
God I hate Word.

**Comment by opoudjis** [comment]
Ah, Word. 

I just wrote on Html2Doc, "I have no idea what the lfo1 attribute is for" in the Word CSS.

Looks that this is what it's for.

**Comment by opoudjis** [comment]
Fixed in html2doc
