### ISSUE TITLE
Example and Note run-in issue

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-iso#120]
```
[example]
<<CVE>>, <<CERT-EU>>, <<NCSC-FI>>, <<JVN>> and <<AUSCERT>> are examples of data
sources providing generic technical vulnerability data.

NOTE: Vulnerability data sources used in an assessment may be queried via online services,
or even using portable, static, files that use a vulnerability description language such
as the Open Vulnerability and Assessment Language (OVAL).
```

This gets rendered as:
<img width="866" alt="screen shot 2018-03-09 at 4 33 06 pm" src="https://user-images.githubusercontent.com/11865/37197959-9877209c-23b7-11e8-80d1-a333b6cc1b7d.png">

**Comment by opoudjis** [comment]
I was allowing note to be folded into preceding block if non-final in a clause, which makes sense if the preceding block is a paragraph. It doesn't make sense if it is a delimited block though: if you wanted the note included in that delimited block, you would have included it already.

**Comment by ronaldtse** [comment]
Got it. As long as there’s an explanation in the README I’m happy to follow syntax :wink:
