### ISSUE TITLE
"Clicking" on a reference defined in References does not bring them to the reference

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-iso#122]
For example, if you cite a reference defined in References, and in Word if you click the citation, it does nothing.

```
... text
<<NVD>>

[bibliography]
= References

* [[[NVD,National Vulnerability Database]]]  http://nvd.nist.gov
```

It just becomes an empty hyperlink. It seems like we need to set Word Bookmarks on each of these references, and then have the citation hyperlink "link" to the corresponding bookmark.

**Comment by opoudjis** [comment]
Another update to Html2Doc
