### ISSUE TITLE
Introduce Appendixes distinct from Annexes

### ISSUE THREAD

**Issue by opoudjis** [riboseinc/asciidoctor-iso#125]
They appear in ISO/IEC DIR 1

**Comment by opoudjis** [comment]
They appear as subcategories of Annexes: they are in effect annexes of annexes, rather than a sister class of annexes. I think that's silly, but I'll add them in.

**Comment by opoudjis** [comment]
For i18n, need the Chinese for Appendix, as distinct from Annex.

**Comment by opoudjis** [comment]
Implemented, now just need to rspec isodoc test; will get to it this evening.

**Comment by ronaldtse** [comment]
Appendix is 附录，Annex is 附件。

**Comment by opoudjis** [comment]
Done
