### ISSUE TITLE
Update TermsSection / DefinitionSections according to isodoc-models

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-iso#126]
Update according to this change: https://github.com/riboseinc/isodoc-models/commit/96ce060d6c262b8172aba552c035e9768d647376

* `TermsSection` now only contains `terms` (`TermCollection`) (removed "subsections: TermSection")
* Added `DefinitionSection` that only contains `definitions` (`DefinitionCollection`) (for symbols/abbrevs)
* `DefinitionElement` has been moved from Text model into `<<Terms>> Definition`

Related to: https://github.com/riboseinc/isodoc-models/issues/32

**Comment by opoudjis** [comment]
> TermsSection now only contains terms (TermCollection) (removed "subsections: TermSection")

Done

**Comment by opoudjis** [comment]
Definitions: done.
