### ISSUE TITLE
Update according to IsoBibItem.ics cardinality change

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-iso#127]
IsoBibItem.ics is Ics[1..*] instead of Ics[1]

https://github.com/riboseinc/isodoc-models/commit/639b52cf11a73771739d74fe4ac2a14b224d4e76

Related to https://github.com/riboseinc/isodoc-models/issues/33

**Comment by opoudjis** [comment]
asciidoctor-iso currently makes no use of ics, so there is nothing to change.

asciidoctor-gb does; I will note that they should be comma delimited in the readme.

**Comment by ronaldtse** [comment]
@opoudjis interesting. ISO does assign ICS codes (often multiple) to every standard, but it seems that they’re not reflected in the content. However due to the fact they’re assigned, they are represented in the IsoBib model. Maybe we should also support it in this gem to make a normal IsoBib identical to the metadata IsoBib in an IsoDoc.

**Comment by opoudjis** [comment]
Will add to the gem, the same way it is added to asciidoctor-gb, but it is only going to show up in the XML.

**Comment by ronaldtse** [comment]
Sounds great. Thanks!
