### ISSUE TITLE
Guide to creating gems for new Isodoc standards

### ISSUE THREAD

**Issue by opoudjis** [riboseinc/asciidoctor-iso#131]

**Comment by ronaldtse** [comment]
Audience:
* Standards orgs ("SDOs")
* Companies

Questions to answer in the guide:

* How can I adopt the StanDoc specification for my own publications, i.e. "RiboseDoc" as inherited from StanDoc or IsoDoc? (will we provide a few templates for them to choose, like IsoDoc or even RfcDoc?)
* How do I adopt this excellent publishing toolchain?
* How can I style the resulting output? (HTML, Word, PDF)
* How can I localize the resulting output?
* I can translate my specifications into IsoDoc XML myself (i.e. I don't like AsciiDoc, or I already have my toolchain). Can I only use IsoDoc XML to produce pretty output?

**Comment by opoudjis** [comment]
https://github.com/riboseinc/asciidoctor-iso/wiki/Gem-Customisation-Guide
