### ISSUE TITLE
Unnumbered bullet lists ("dash lists") should not be indented

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-iso#132]
Now:

![screen shot 2018-04-10 at 12 07 06 pm](https://user-images.githubusercontent.com/11865/38535762-c0179adc-3cb7-11e8-89aa-885db3230c05.png)

Correct:
![screen shot 2018-04-10 at 12 07 11 pm](https://user-images.githubusercontent.com/11865/38535765-c2dde5a0-3cb7-11e8-9267-03deeb4e3629.png)

**Comment by opoudjis** [comment]
Issue I've just rectified in GB (https://github.com/riboseinc/asciidoctor-gb/issues/57): `<ol>, <ul>` need to have their left margin explicitly set to 0 in Word stylesheets, and the inherited stylesheets were expecting `<p>` for lists instead.
