### ISSUE TITLE
Allow setting a (pseudo)4-part title

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-iso#135]
This title: "Information technology -- Security techniques -- Encryption algorithms -- Part 5: Identity-based ciphers" (https://www.iso.org/standard/59948.html)

Is a 3 part title with the "middle" part split into two.

```
:title-intro-en: Information technology
:title-main-en: Security techniques -- Encryption algorithms
:title-part-en: Part 5: Identity-based ciphers
```

This generates this title:

```
Information technology — Security techniques -- Encryption algorithms -- Part 5: Identity-based ciphers 
```

The middle "--" is used instead of the long dash. I propose we use "--" in source to represent long dashes, and at the end when generating HTML / Word we use "—". The official title as you see on ISO, uses "--".

**Comment by opoudjis** [comment]
The conversion of `--` to `—` should be automatic in Asciidoctor. Will check.

**Comment by opoudjis** [comment]
Right, it isn't automatic because doc headers are not subject to Asciidoctor's substitutions. Will postprocess in code.

**Comment by opoudjis** [comment]
All normal special character replacements that happen in Asciidoctor now apply to title components from the document header.
