### ISSUE TITLE
Get started quickly guide

### ISSUE THREAD

**Issue by opoudjis** [riboseinc/asciidoctor-iso#136]

**Comment by ronaldtse** [comment]
* Installation instructions
* How to setup a repo
* Point to https://github.com/riboseinc/isodoc-rice/
* Demonstrate AsciiDoc syntax that is supported
* Demonstrate AsciiISO specific syntax (like the T&D ones)
* how to add references (normative, informative)
* how to add annexes
* how to add images
* how to add equations

**Comment by opoudjis** [comment]
https://github.com/riboseinc/asciidoctor-iso/wiki/Quickstart-Guide
