### ISSUE TITLE
Integrate with PlantUML

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-iso#138]
[PlantUML](http://plantuml.com) is an ASCII-based UML diagram processor that converts textual UML into PNG output.

This ticket is to integrate these PlantUML text snippets into AsciiISO, and most importantly, AsciiCSD.

**Comment by ronaldtse** [comment]
On macOS you can install with `brew install plantuml`.

Sample run.

x.txt (I prefer calling this extension ".plm" (PLantumL) (pronounced as "plum").

```
@startuml
Alice -> Bob: test
@enduml
```

Type `plantuml x.txt` and you'll get `x.png`.

**Comment by opoudjis** [comment]
Implemented macro in Asciidoctor-ISO. Will spec and test. Macro is literal with class attribute `[plantuml]`:

````
[plantuml]
....
@startuml
Alice -> Bob: Authentication Request
Bob --> Alice: Authentication Response

Alice -> Bob: Another authentication Request
Alice <-- Bob: another authentication Response
@enduml
....
````

The `@startuml, @enduml` will be supplied if missing.

**Comment by ronaldtse** [comment]
Excellent!
