### ISSUE TITLE
[example] syntax causes wrong styling in the right column

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-iso#140]
[example] syntax produces you a table, where the content is on the right side.

However, now the content on the right side is not styled (Times New Roman, 12) vs the left side which is correct (Cambria, 10).

NOTE: This only happens on some documents. Some documents have the correct styling. I wonder why?

**Comment by opoudjis** [comment]
Moved to https://github.com/riboseinc/isodoc/issues/53
