### ISSUE TITLE
Storage of the metadata of the document

### ISSUE THREAD

**Issue by andrew2net** [riboseinc/asciidoctor-iso#143]
@ronaldtse you said here about storage metadata  https://github.com/riboseinc/isobib/issues/18#issuecomment-382914368
Do you mean storage document attributes in the source ADOC file?

**Comment by ronaldtse** [comment]
So the purpose of asciidoctor-iso is used to convert AsciiDoc into ISODOCXML. 

In the input AsciiDoc format, metadata (title, author, dates, technical committee, etc) is provided as AsciiDoc document attributes. All this metadata information is placed inside ISODOCXML in the IsoBib XML format. 

The second usage is for “references”. In AsciiDoc, you can cite an ISO document like <<ISO27001>> which should automatically use the IsoBib gem to fetch the “ISO/IEC 27001:2013” document metadata. When the AsciiDoc is compiled as ISODOCXML, the information retrieved via IsoBib should stay inside the ISODOCXML. Hence this is “storage” of the IsoBib information.
