### ISSUE TITLE
Change date/from to date/on for point dates

### ISSUE THREAD

**Issue by opoudjis** [riboseinc/asciidoctor-iso#145]
Impacts isodoc gem as well

**Comment by opoudjis** [comment]
@andrew2net , warning you of this upcoming modelling and serialisation change (https://github.com/riboseinc/bib-models/issues/5)

We have been modelling date ranges as date/from, date/to. We have been modelling point dates as date/from. So 1987–1988 = `<date><from>1987</from><to>1988</to></date>`; 1987 = `<date><from>1987</from></date>`. 

The problem is that an open range like 1987- is naturally modelled as `<date><from>1987</from></date>`; and using "from" to indicate a point date is artificial and confusing.

As a result, I will be changing the model and serialisation: point dates will be modelled as date/on, not date/from. So 1987 will become `<date><on>1987</on></date>`, and `<date><from>1987</from></date>` will mean only 1987-.

This will of course impact your code as well. Could you create the relevant tickets?

**Comment by andrew2net** [comment]
@opoudjis do we need to remove date/to?

**Comment by opoudjis** [comment]
@andrew2net no, we just keep it for date ranges
