### ISSUE TITLE
Review fetch_isobib branch

### ISSUE THREAD

**Issue by opoudjis** [riboseinc/asciidoctor-iso#152]

**Comment by opoudjis** [comment]
lib/asciidoctor/iso/cleanup_ref.rb

>  x["citeas"] = @anchors&.dig(x["target"].upcase, :xref)

I question the need for this; there will be components of citations, such as "All Parts", that will not be in uppercase. What did you have in mind with the upcase?

**Comment by andrew2net** [comment]
@opoudjis `@archors` contains an uppercased key which came from Isobib. For example, ISO216. Without upcase `x["target"]` doesn't match the kye. Suppose we should work around it somehow.

**Comment by opoudjis** [comment]
I'll require an ISO or IEC prefix in order to uppercase; ok.

**Comment by opoudjis** [comment]
I'll flag all keys retrieved from isobib, and uppercase only those. (That will deal with the case where there was an ISO reference retrieved without internet, which would not alter the case.)

**Comment by opoudjis** [comment]
The key for an ISO reference can be completely arbitrary; I could have `[[[reference78,ISO 712]]]`, and only the "ISO 712" serves to identify it as an ISO reference. Uppercasing the anchor will not make a difference in that case. So I will postprocess the result received from isobib, to replace the supplied anchor with the document's anchor.

**Comment by ronaldtse** [comment]
@opoudjis @andrew2net can we have documentation for how to trigger auto-bibliography?

* e.g. keywords found in anchor (e.g. ISO, IEC...?)

**Comment by opoudjis** [comment]
Moved that query to https://github.com/riboseinc/asciidoctor-iso/issues/153
