### ISSUE TITLE
Detect stale entries

### ISSUE THREAD

**Issue by opoudjis** [riboseinc/asciidoctor-iso#156]
From https://github.com/riboseinc/asciidoctor-iso/issues/155

If a bibliographic entry is undated and cached in global cache,

* Fetch it anyway (!)
* If its date is more recent than the cached entry, overwrite it
* And, if there is a corresponding local cache entry, overwrite that too

... And I don't think this is a good idea: if we reload each undated ISO entry each time to check whether it's been updated, there's not much point caching them to begin with, given how time consuming the searches are. 

I'd favour storing the date of last fetch of each cached entry, and doing a refresh only if they're say a couple of months old, rather than every time the code is run. @ronaldtse ?

**Comment by opoudjis** [comment]
First step: inject date last fetched into biblio cache. Biblio cache entries will now have two attributes: "fetched", and "bib".

**Comment by opoudjis** [comment]
Done. Entries expired if they have no date of publication (= Most Recent reference), and were fetched more than 60 days ago.

**Comment by ronaldtse** [comment]
@opoudjis are we going to move this functionality to the `isobib` / `relaton-iso` gem?

**Comment by opoudjis** [comment]
No, because it is functionality specific to the caching of references, which is out of scope of isobib as it stands.

**Comment by ronaldtse** [comment]
Maybe the Relaton gem system should support fetching the references, and also the caching of them. Then the asciidoctor-iso processor only needs to asks Relaton for these things.
