### ISSUE TITLE
Reversed obligation behavior in [appendix] tag

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-iso#159]
Currently the `[appendix]` tag will mark an annex as normative by default, contradictory to what is said in the Wiki (https://github.com/riboseinc/asciidoctor-iso/wiki/Guidance-for-authoring).

I think the behavior is acceptable, so we should change the Wiki instead.

**Comment by opoudjis** [comment]
Done in both Guidance and Quickstart doc.
