### ISSUE TITLE
Supporting document stage names and display of stage on document

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-iso#16]
In ISO, a draft proceeds through "stages" until publication. In each stage, there is a different designation to the draft. For example, in stage 20, the draft is called a WD (for "Working Draft").

The corresponding stages of a document/draft are shown below (stage name: draft name):
* 10 (Proposal: NWIP "New Work Item Proposal")
* 20 (Preparatory: WD "Working Draft")
* 30 (Committee: CD "Committee Draft")
* 40 (Enquiry: DIS "Draft International Standard")
* 50 (Approval, FDIS "Final Draft International Standard")
* 60 (Publication: IS "International Standard)

However, a draft can be re-done and re-circulated in the same stage if it has not been approved to the next stage. Usually this is done by adding a suffix `X` to the draft name, e.g., "WD" => "WD2", and this applies to all the stages except 60 (there cannot be an "IS2").

Moreover, the draft name (e.g., "DIS") needs to appear in the first page of the draft to indicate the draft stage, and also in the reference number at the footers. 

e.g.,
```
Document type: International Standard
Document subtype:
Document stage: (60) Publication
Document language: E

Document type: International Standard
Document subtype: Amendment
Document stage: (30) Committee
Document language: E

Document type: International Standard
Document subtype:
Document stage: (50) Approval
Document language: E

Document type: Technical Report
Document subtype:
Document stage:
Document language: E

Document type: International Standard
Document subtype:
Document stage: (40) Enquiry
Document language: E

Document type: International Standard
Document subtype: Amendment
Document stage: (20) Preparatory
Document language: E

// Sometimes there is a non-standard draft stage e.g, this is a "preCD"
Document type: International standard
Document subtype: if applicable
Document stage: (20) Preparation
Document language: E
```

The reference number can be like this:

```
ISO/IEC FDIS 27017:2015(E)
ISO/IEC preCD 29134
ISO/IEC WD1 29147
ISO/IEC WD3 27021
```

**Comment by opoudjis** [comment]
Most of this has been done, except for recirculation, which will require addition to document model. #24 . So, `:draft: 2`, and `:draft: 1` would be ignored as the default draft iteration.

Where does the pre in preCD come from? Can I make this a `draft: 0`?

**Comment by ronaldtse** [comment]
Agree, we should make this a "preXX" as `draft: 0`.

**Comment by opoudjis** [comment]
1, 2, pre, or pre2

**Comment by ronaldtse** [comment]
Actually, the `preXXN` isn't good usage because you can also have multiple `preWD2` revisions.

Maybe the better idea is to replace it with the `revision` date with a `:draft: Y.Z`.  So `preXXN` should just be `:stage: XX` + `:draft: Y.Z` + `:revision: 20180202` (where `Y` is the previous draft number, `Z` is the sub-draft number)?

**Comment by ronaldtse** [comment]
@opoudjis any thoughts here?

**Comment by opoudjis** [comment]
OK with adding draft as document attribute

**Comment by opoudjis** [comment]
Implemented with templates and `:draft:` document attribute.

**Comment by ronaldtse** [comment]
Very very nice. Thank you!
