### ISSUE TITLE
Suppress year in generation of ISO references if not in original citation

### ISSUE THREAD

**Issue by opoudjis** [riboseinc/asciidoctor-iso#160]
Unexpected consequence of isobib. Now that the date of the latest ISO spec is included in the search result, it is being included in the generated document. But that's actually wrong: references are meant to be undated, in order to allow reference to the latest version.
 
So I think the reference anchor in the XML should include an attribute to suppress the year in display. You OK with that?
 
e.g. `<bibitem type="international-standard" id="ISO2146" suppress-year="true">`
 
If I cited `* [[[ISO712,ISO 712]]], Cereals and cereal products -- Determination of moisture content -- Reference method`, I should not be getting back ISO 712: 2009 in the reference list

**Comment by ronaldtse** [comment]
@opoudjis that's totally reasonable -- however I'd prefer `suppress-year` not to pollute the `<bibitem>` itself. At the citation level?

**Comment by ronaldtse** [comment]
> If I cited * [[[ISO712,ISO 712]]], _Cereals and cereal products -- Determination of moisture content -- Reference method_, I should not be getting back ISO 712: 2009 in the reference list

Agree. In this case I feel we should encode the "suppress-year" in the `[bibliography]` section instead of at the `<bibitem>` level.

**Comment by opoudjis** [comment]
The problem is that it is specific to a bibliographic item, though in the context of a bibliography. So it can't be an attribute of the bibliography. The natural course is to make it an attribute of the ISO subclass of bibitem.  The alternative is to create an element or attribute somewhere else listing ISO references whose years will be omitted; that's awkward, but doable.

**Comment by ronaldtse** [comment]
Agree, in this case I think the `<bibitem>` should be for "ISO 712" instead of "ISO 712:2009". Is that possible?

**Comment by opoudjis** [comment]
Well, we're making up the bibitem, so we can populate it however we choose. The question is, as with All Parts, whether we do populate it with all the content fetched from isobib, or we alter it.

Now, in ISO standards (and this is an ISO-standard thing, not a general bibliographic convention), "ISO 712" means "latest version of ISO 712", and remains valid even when the standard is updated; if you regenerate the document, it will legally fetch the 2020 version of the specification.

But if the reference is to the latest version, as opposed to the 2009 version, then the XML should not include information specific to 2009: that's misleading.

That's not how references are supposed to work. A bibliographic reference, at the level of detail bibitem has, is always timebound to a specific version of a publication. But ISO in fact sidesteps that particularity: that's why its references consist only of the title—that's the only bit that is likely to stay the same between versions.

So I think the solution is to remove edition-specific information in the included XML references for an undated reference. That includes not only the date of publication, but anything liable to change between versions of the standard, including the abstract. We can retain the URL, because there are no links to generic versions. It is optimistic to assume that the part structure of the standard will remain the same—that a standard without parts will remain without parts, that part 1 this version will correspond to part 1 next version; but the use of the undated title in ISO actually makes that assumption.

So, ISO's undated references introduce a complication in referencing that is not normally there. We have the following options:

* We make the bibitem reference ISO 712 instead of ISO 712:2009, by removing all information from the bibitem that are specific to 2009: the year, and the abstract.
* We keep all the information in the bibitem reference fetched from ISO 712:2009, but we flag (on an attribute of bibitem, or on an extraneous element) that the year is to be omitted from the rendering of the element.

The former makes the XML more accurate, but also more artificial (publications are not undated). The latter makes dropping the date an artifice of presentation, rather than part of the meaning of the XML.

So you tell me.

**Comment by ronaldtse** [comment]
I have a third option, which you may consider superfluous, is to have an option 1 with a document-relation to option 2. This way we don't lack any information. I believe the "extraneous element" of linking a "element citation" to a "document citation" to a "bibliography" may be necessary after all.

i.e.

1. my text refers to <<ISO712,clause 3.3>> (this is the cross-ref element)
2. since the text uses <<ISO712>>, there is a document citation that links the document to cite ISO712. (this is the extraneous element we don't have now)
3. since there is a document citation we embed the ISO712 <bibitem> into the document. (this is purely for inclusion of bibitem data)

Step 3 could be replaced with an external source of <bibitem> too.

**Comment by opoudjis** [comment]
It's overcautious, but I can do it. Your explication is confused though: let me try this:

````
<eref type="inline" bibitemid="ISO712" citeas="ISO 712"/>
....
<bibitem type="international-standard" id="ISO712">
...
<docidentifier>ISO 712</docidentifier>
<!-- date stripped -->
  <language>fr</language>
  <script>Latn</script>
<!-- abstract stripped -->
<relation type="hasVersion">
    <bibitem>
       ...
       <docidentifier>ISO 712</docidentifier>
       <date type="published">
          <on>2009</on>
        </date>
       ...
        <language>fr</language>
         <script>Latn</script>
  <abstract format="plain" language="en" script="Latn">ISO 712:2009 specifies a routine reference method for the determination of the moisture content of cereals and cereal products.ISO 712:2009 applies to: wheat, rice (paddy, husked and milled), barley, millet (Panicum miliaceum), rye, oats, triticale, sorghum in the form of grains, milled grains, semolina or flour.The method is not applicable to maize and pulses.</abstract>
    </bibitem>
````

Is that OK? The full, ISO 712:2009 reference is embedded through docrelation inside the redacted ISO 712 reference; but because it's embedded, there's no risk of ISO 712:2009 accidentally being cited, as it is now.

If that's ok, I'll proceed with implementing it.

**Comment by opoudjis** [comment]
Proceeding. @ronaldtse concerned that the embedded original would fall out of sync with an independently cited instance of the part document (e.g. citing both ISO 712 and ISO 712:2009 in the same document)—but that is highly unlikely. @ronaldtse wanted to see ISO 712:2009 as an independent top-level item, to preserve its integrity; but the bibliography should only be enumerating at top level items that are actually cited.

**Comment by opoudjis** [comment]
I've implemented this, with the original reference embedded for both yearless and all-parts references, in iso-bib-item.
