### ISSUE TITLE
Terms and defs: IEV sourced terms not showing up

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-iso#164]
Terms sourced from "IEV" terms are not showing up at all in the resulting HTML.

```adoc
[[term-time]]
===== time

mark attributed to an _instant_ (<<term-instant>>) by means of a specified time scale (<<term-time-scale>>)

[.source]
IEV 113-01-12, modified -- preferred term "`time`" placed prior to "`date`", replaced "`date`" with this preferred term "`time`" in Note 1, omission of Note 2, renumbering of Note 3 to Note 2, added Note 3 and Note 4 to entry
```

**Comment by opoudjis** [comment]
Illegal format:

https://github.com/riboseinc/asciidoctor-iso/wiki/Guidance-for-authoring

> The definition is then followed by a citation for the term, marked with a [.source] role attribute).

"Citation" means `<<`, so:

````
[.source]
<<ISO7301,section 3.2>>, The term "cargo rice" is shown as deprecated,
and Note 1 to entry is not included here
````

All instances of "IEV 113-01-12" etc need to be replaced with an Asciidoc crossreference to the document. (I can't suggest one, since you haven't actually created any references for the IEV documents yet.)

**Comment by ronaldtse** [comment]
So the IEV is not a “document”, it is a term base. “IEV 113-01-12” is a reference to a specific term. Maybe Metanorma should have a syntax that allows citing IEV terms?

**Comment by opoudjis** [comment]
.... 

This is the first I've heard of term bases, and this is an entire class of entities you're talking about adding to the model. I think the answer is no: it makes no sense to treat `<<ISO7301,section 3.2>>` any different from `<<IEV,section 113-01-12>>`. The source contains a citation, and term bases are just as much a citable reference as a standards document is.

**Comment by ronaldtse** [comment]
Example of IEV sourced terms in ISO document:
https://www.iso.org/obp/ui/#iso:std:iso:14990:-1:ed-1:v1:en

**Comment by opoudjis** [comment]
Will handle as <<IEV,113-01-12>>. Will provide documentation that IEV reference needs to be provided. Will remove IEV reference from rendering (in ISO documents, at least.) There will be an iev gem to validate IEV entries against the IEV website.

**Comment by ronaldtse** [comment]
Thank you @opoudjis !

**Comment by ronaldtse** [comment]
Here you go: https://github.com/riboseinc/iev
