### ISSUE TITLE
Terms and definitions with symbols / abbreviations

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-iso#166]
The code is generating a wrong "Terms and Definitions" section when we use an alternative form of the title.

Section 3 can be one of these titles  (as allowed by ISO Directives Part 2):

*  "Terms and definitions"
*  "Terms, definitions and symbols"
*  "Terms, definitions and abbreviations"
*  "Terms, definitions, symbols and abbreviations"

However, this content is generating conflicting output:

```adoc
== Terms, definitions and abbreviations

=== Terms and definitions
...blah

=== Abbreviations
...blah
```

The output is:
* 3 Terms and Definitions
* 3.1 Terms and Definitions
* 3.2 Abbreviations

Which is quite off.

**Comment by opoudjis** [comment]
I had only allowed for "Terms and definitions", "Terms, definitions, symbols and abbreviations".

**Comment by ronaldtse** [comment]
Hmmm, maybe you're right -- for sure it's a title given in the example of Directives Part 2.

> The symbols do not need to be numbered. For convenience, the symbols and abbreviated terms may be combined with the terms and definitions in order to bring together terms and their definitions, symbols and abbreviated terms under an appropriate composite title, for example “Terms, definitions, symbols and abbreviated terms”.

But given it is an "example" of "an appropriate composite title", should we allow other variations?

I'll change my doc for now. Thanks @opoudjis !

**Comment by opoudjis** [comment]
Sorry: "terms, definitions, symbols and abbreviated terms", which is the exact wording from ISO/IEC DIR 2. 

I will allow the other permutations.

**Comment by ronaldtse** [comment]
@opoudjis I'm not seeing this fixed:

```adoc
== Terms, definitions, symbols and abbreviations

=== Terms and definitions

==== blah
```

Still gives me this:
![screen shot 2018-06-14 at 11 34 29 am](https://user-images.githubusercontent.com/11865/41390147-f0572aea-6fc6-11e8-8475-f93ed723c170.png)

Also, "Terms and Definitions" should be "Terms and definitions" (title cased).

**Comment by opoudjis** [comment]
The title of the top-level clause exercises its own judgement:

* If the clause includes a "symbols and abbreviated terms" subclause, it is titled "terms, definitions, symbols and abbreviated terms"
* If the clause does not include a "symbols and abbreviated terms" subclause, it is titled "terms and definitions".

The title thereby reflects what the clause actually contains, and I would argue this is a feature not a bug. If you add a `=== Symbols and abbreviated terms` to the foregoing, you will see the desired title change.

**Comment by opoudjis** [comment]
Casing: fixing throughout.

**Comment by ronaldtse** [comment]
@opoudjis I'm not seeing this issue fixed?

I have this section:
```adoc
[[terms]]
== Terms, definitions, symbols and abbreviated terms

[source=ISO5127]
=== Terms and definitions

==== blah

Definitions.

=== Symbols and abbreviated terms

For the purposes of this document, the following symbols and abbreviated terms apply.

"`[`", "`]`":: Square brackets are used to enclose IPA phonetic symbols.

IPA:: International Phonetic Alphabet

```

And the output is:

![screen shot 2018-07-01 at 5 15 00 pm](https://user-images.githubusercontent.com/11865/42132848-520a256a-7d52-11e8-9ce1-3eeaec7f5df5.png)

And the resulting symbols section becomes this:

![screen shot 2018-07-01 at 5 14 52 pm](https://user-images.githubusercontent.com/11865/42132849-5237134a-7d52-11e8-832f-afbce0cdb309.png)

**Comment by ronaldtse** [comment]
(the XML appears in both HTML and Word Doc output)

**Comment by ronaldtse** [comment]
And in this situation, where should the `[SOURCE=xxx]` apply to:

`== Terms, definitions, symbols and abbreviated terms`

or

`=== Terms and definitions` ?

**Comment by ronaldtse** [comment]
Thanks @opoudjis . Could we document the correct behavior either in the README or the quick start guide so users know how to use this?

**Comment by ronaldtse** [comment]
Also on where the `[SOURCE]` attribute should be placed. Thanks!

**Comment by ronaldtse** [comment]
@opoudjis for the record, the ToC / section headers of "Terms, definitions, symbols and abbreviated terms" is still not appearing (and the "Terms and Definitions" in 3.1 has the "Definitions" in the wrong case). The `[SOURCE]` works and the definition list in `=== Symbols and abbreviated terms` work.

**Comment by opoudjis** [comment]
"Terms, definitions, symbols and abbreviated terms" now added correctly.

**Comment by opoudjis** [comment]
The problem with the subclause "Terms and Definitions" is the following:

* The top-level clause title for T&D is fixed: it is _Terms and definitions_ if it does not include a symbols subclause, and _Terms, definitions, symbols and abbreviated terms_ if it does.
* The top-level symbols clause title is fixed: it is _Symbols and abbreviated terms_
* The symbols subclause is likewise fixed.

But! a terms subclause title is _not_ fixed. It could be _Default Terms_, _Normal Terms_, _Terms and Definitions_, _Terms and definitions_, or anything else. So I cannot import the default label and overwrite the subclause title, the way I do in the other cases.

I'm also reluctant to change the case of titles to sentence case: I won't know where the proper names are.

You may not like this, but I'm afraid there is no code fix to this one, just a process fix (telling people to use sentence case always in titles, for consistency). The special titles which the gem detects are detected case-insensitive, though they are written to ISO XML in title case.

... Is that OK?

**Comment by ronaldtse** [comment]
> The top-level clause title for T&D is fixed: it is Terms and definitions if it does not include a symbols subclause, and Terms, definitions, symbols and abbreviated terms if it does.

This is good. 

> The top-level symbols clause title is fixed: it is Symbols and abbreviated terms
> The symbols subclause is likewise fixed.

Good too.

> But! a terms subclause title is not fixed. It could be Default Terms, Normal Terms, Terms and Definitions, Terms and definitions, or anything else. So I cannot import the default label and overwrite the subclause title, the way I do in the other cases.

But the code now generates the text "Terms and Definitions" which is wrong (because it should be "Terms and definitions"). We can allow overriding the label but definitely should not produce "Terms and Definitions". In the sample document we have, it is designated as "Terms and definitions" but the output still becomes "Terms and Definitions".

**Comment by opoudjis** [comment]
I see what's happened: the titlecase text is coming out of asciidoctor-iso. I'll stop it doing that, it's unnecessary.

**Comment by opoudjis** [comment]
Fixed.

**Comment by ronaldtse** [comment]
Thanks!

**Comment by opoudjis** [comment]
Updated guide.
