### ISSUE TITLE
Bibliography rendering of text missing space for non-italicized words

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-iso#169]
```
[bibliography]
== Bibliography
* [[[IEV,IEV]]], IEC 60050 (all parts), _International Electrotechnical Vocabulary_, available at http://www.electropedia.org
```

This is rendered in the Bibliography as:
```
[1] IEV,IEC 60050 (all parts), International Electrotechnical Vocabulary, available at http://www.electropedia.org
```

But there should be a "space" between "IEV," and "IEC".

**Comment by opoudjis** [comment]
I can't replicate this any more, because I'm now suppressing rendering of any reference named IEV. But I have replicated it with `[[[IEV,XYZ]]]`

**Comment by opoudjis** [comment]
Fixed in isodoc: was affecting non-ISO references in bibliography not terminating in numeral.
