### ISSUE TITLE
Abbreviations listed in HTML vertical alignment issue

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-iso#170]
They list correctly in Word, but in HTML the text in the second column is shifted up (or the text in the first is shifted down).

![screen shot 2018-06-14 at 12 05 09 pm](https://user-images.githubusercontent.com/11865/41391090-45fb35aa-6fcb-11e8-8610-c1100637d2ed.png)

**Comment by opoudjis** [comment]
I had fixed this months ago by introducing valign to the definition list tables; I'll see why it's gone missing.

**Comment by opoudjis** [comment]
Added `dt p { margin-top: 0px;}` to `dd p { margin-top: 0px;}` in stylesheets.
