### ISSUE TITLE
How to check version of asciidoctor-iso

### ISSUE THREAD

**Issue by beautifulnature** [riboseinc/asciidoctor-iso#172]
How to check version of asciidoctor-iso from comand line?
How to work with different versions from comand line?

**Comment by opoudjis** [comment]
We have not implemented versioning in ISO; but we should.

Different versioning would involve importing different versions of the gem; I'll document that.

**Comment by beautifulnature** [comment]
Thankyou. This project is excellent.

**Comment by opoudjis** [comment]
Have realised version reporting in the metanorma script:

````
metanorma -t iso -v
````

Now returns: "Asciidoctor::ISO 0.8.1/IsoDoc 0.7.1"
