### ISSUE TITLE
error while generating xml

### ISSUE THREAD

**Issue by beautifulnature** [riboseinc/asciidoctor-iso#173]
error while using $ asciidoctor -b iso -r 'asciidoctor-iso' a.adoc  # ISO XML output,

![image](https://user-images.githubusercontent.com/36604320/41483991-c381f850-70f8-11e8-9a3d-b58b72b18ad6.png)

**Comment by ronaldtse** [comment]
@beautifulnature this is a known problem using Ruby 2.5 -- it's been fixed in master but not yet released. (ping @opoudjis)

However, the real problem is the command. Your command should be this:

```sh
$ metanorma -t iso iso-rice-en.adoc
```

Direct access to the `asciidoctor-iso` executable is no longer supported.

**Comment by beautifulnature** [comment]
thankyou. I followed instructions by you.
1) I installed metanorma
2) run under Ruby 2.4.0. 
3) installed java, is one of its dependency.

It's worked like charm. Thankyou.

**Comment by ronaldtse** [comment]
@beautifulnature just to let you know, we've just updated our metanorma-setup script (https://github.com/riboseinc/metanorma-macos-setup) to handle the full setup flow. Thanks for the report again!
