### ISSUE TITLE
IS stage document should not have WD/CD warning

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-iso#177]
Non WD/CD stage documents such as 60 (IS) should not have this warning (and the stage name), which is produced today:

```
IS stage

Warning for WDs and CDs

This document is not an ISO International Standard. It is distributed for review and comment. It is subject to change without notice and may not be referred to as an International Standard.

Recipients of this draft are invited to submit, with their comments, notification of any relevant patent rights of which they are aware and to provide supporting documentation.

```

**Comment by opoudjis** [comment]
Just WD/CD? Or should it apply to all documents before 60?

**Comment by ronaldtse** [comment]
Great question. Let's apply it to all before 60...

**Comment by opoudjis** [comment]
As it turns out, this conditional behaviour has already been implemented in GB.

**Comment by ronaldtse** [comment]
Therefore we should back port those features (I think there's more) from GB into ISO 😉

**Comment by opoudjis** [comment]
Fixed in isodoc. Turns out that the Liquid wouldn't have worked in GB either; `>` was being mangled into `&lt;`.
