### ISSUE TITLE
Non-header section title should not be bolded

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-iso#178]
In some ISO documents, a section header is not a real header, but a numbered clause. In this case, the text is NOT bolded. We need a way to achieve this.

Screenshot (desired output):

![screen shot 2018-06-27 at 1 19 36 am](https://user-images.githubusercontent.com/11865/41928559-385c3dea-79a8-11e8-8056-a3ed2e254687.png)

Code (which produces bolded title):

```adoc
[[nonconformities]]
=== Nonconformity and corrective action

[[nonconformities-reqs]]
==== When a nonconformity occurs, including any arising from complaints, the organization shall:

. react to the nonconformity and, as applicable:

** take action to control and correct it;

** deal with the consequences;
```

**Comment by opoudjis** [comment]
No. In the rice document, such clause numbers are always bolded:

<img width="549" alt="image" src="https://user-images.githubusercontent.com/1911039/41963430-ea9fdb32-7a3a-11e8-94d8-d4621a58e7ab.png">

I've done this deliberately to emulate that document's formatting.

**Comment by opoudjis** [comment]
... Hang on, I've misunderstood: you want to generate that output, you're not complaining about it. The way to generate it in asciidoctor is as:

````
[[nonconformities-reqs]]
==== {blank}

When a nonconformity occurs, including any arising from complaints, the organization shall:
````

You can see that in our Asciidoctor encoding of the Rice Model document.

**Comment by ronaldtse** [comment]
Ahhh good point. Let's make sure this is in the Authoring Guide. Thanks!

**Comment by opoudjis** [comment]
It was already in there, I'm making it more explicit.
