### ISSUE TITLE
HTML output lowercase numbered list not showing labels

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-iso#179]
Official rendering (of a published document in PDF):

![screen shot 2018-06-27 at 1 22 39 am](https://user-images.githubusercontent.com/11865/41928727-c07ef640-79a8-11e8-9c09-1dcf5dfdd114.png)

Current HTML output (notice the `a)` etc is missing):
![screen shot 2018-06-27 at 1 22 45 am](https://user-images.githubusercontent.com/11865/41928730-c441ba4c-79a8-11e8-8296-a31f93009656.png)

**Comment by opoudjis** [comment]
Fixed in isodoc/iso.
