### ISSUE TITLE
Terms and definitions SOURCE citation contains white space

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-iso#181]
Original PDF:

![screen shot 2018-06-27 at 1 32 13 am](https://user-images.githubusercontent.com/11865/41929536-eff4ba70-79aa-11e8-8bc2-9ce034cc3131.png)

HTML output (notice the empty space between `ISO 9000:` and `2015`:

![screen shot 2018-06-27 at 1 32 18 am](https://user-images.githubusercontent.com/11865/41929575-19385e1e-79ab-11e8-9732-b7a0588564e5.png)

Code:

```
[source="ISO9000"]
== Terms and definitions

```

**Comment by ronaldtse** [comment]
Actually the same space occurs in Normative References.

![screen shot 2018-06-27 at 1 42 04 am](https://user-images.githubusercontent.com/11865/41929644-5b994d5e-79ab-11e8-9a29-cbfdccac76c6.png)

**Comment by opoudjis** [comment]
Resolved in Isodoc.
