### ISSUE TITLE
Application of `SOURCE` in Terms and Defs causes XML to appear in HTML/Word

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-iso#184]
I'm applying the `[source=ISO1234]` at the top level and get this output. What's the correct way to doing this?

![screen shot 2018-07-02 at 7 39 21 am](https://user-images.githubusercontent.com/11865/42140210-8caebc90-7dce-11e8-9b10-8e62befe2e03.png)

**Comment by opoudjis** [comment]
obvi, that shouldn't be happening. Where is the source code? Is this in the ext projects?

**Comment by ronaldtse** [comment]
Just shared the draft. Thanks @opoudjis !

**Comment by opoudjis** [comment]
Fixed in isodoc (code was not expecting to find termdocsource where it did, in non-leaf term node) and in asciidoctor-iso (ensure that cleanup of code catches termdocsource in either location).

**Comment by ronaldtse** [comment]
Thanks @opoudjis !
