### ISSUE TITLE
"Symbols  and abbreviated terms" terms/definitions in different vertical alignment

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-iso#186]
See below image, both in HTML and Word output.

![screen shot 2018-07-03 at 11 27 42 am](https://user-images.githubusercontent.com/11865/42197218-536b98c2-7eb4-11e8-88e2-743e3bc9432a.png)

**Comment by opoudjis** [comment]
Fixed in isodoc (stylesheet)

**Comment by ronaldtse** [comment]
Thanks!
