### ISSUE TITLE
Test multiple versions of ruby against all gems in Travis

### ISSUE THREAD

**Issue by opoudjis** [riboseinc/asciidoctor-iso#189]
For gems exclusive to metanorma context (asciidoctor-*, isodoc):
Test back to Ruby 2.4, and make backward compatible back to 2.4. Minimal impact.

For gems not exclusive to metanorma context (e.g. reverse-asciidoctor, html2doc)
Test back to Ruby 2.2, and make backward compatible back to 2.3. That will mean eliminating `.match?` from all such code.

**Comment by opoudjis** [comment]
Checklist of gems:

Metanorma:

* asciidoctor-csand		
* asciidoctor-csd			
* asciidoctor-gb			
* asciidoctor-iso			
* asciidoctor-m3d			
* asciidoctor-metanorma_sample	
* asciidoctor-rfc			
* asciidoctor-rsd			
* gbbib
* iev
* iso-bib-item
* isobib	
* isodoc	
* isoics
* metanorma
* relaton
* rfcbib

Not Metanorma:

* html2doc
* mathml2asciimath
* omml2mathml
* reverse_asciidoctor
* ruby-vobject

**Comment by ronaldtse** [comment]
@andrew2net could you help take care of the Ruby version compatibility of these? Thanks!

* gbbib
* iev
* iso-bib-item
* isobib
* isodoc
* isoics
* rfcbib

**Comment by andrew2net** [comment]
@ronaldtse does it need to merge PR against the master? or just leave it

**Comment by opoudjis** [comment]
Merge is fine.

**Comment by andrew2net** [comment]
@opoudjis did you publish the last html2doc? I'm trying to test isodoc with Ruby 2.3 but html2doc needs Ruby 2.4

**Comment by ronaldtse** [comment]
It already says Ruby 2.3 on Rubygems though. https://rubygems.org/gems/html2doc

**Comment by opoudjis** [comment]
And while we are allowing HTML2doc to parse with 2.3, we require 2.4 of Isodoc, as a core part of Metanorma.

**Comment by opoudjis** [comment]
Btw @andrew2net I have fixed the issue that was preventing gbbib (and all downstream gems) from validating in Travis: I've substituted the gem "duplicate" with "ruby_deep_clone".

**Comment by opoudjis** [comment]
And @andrew2net , (a) again, isodoc is only meant to run with 2.4, 2.5.

**Comment by opoudjis** [comment]
Ruby-vobject bugs: resolved.

Asciidoctor-GB: pending implementation of relaton with gbbib.

asciidoctor-rfc is the only one left. Currently getting stuck timing out on workgroup cache fetch. If that persists, will need to mock.

**Comment by opoudjis** [comment]
Done.
