### ISSUE TITLE
Citations into a bib-item model

### ISSUE THREAD

**Issue by opoudjis** [riboseinc/asciidoctor-iso#19]
> Citations of documents probably deserve a separate issue too since we will need to cite according to some bib-item model...

Eventually, there will be some merger of this gem with an asciidoctor-biblio gem, and/or an abstracted biblio reference model. (I already abstract out the recurring ISO references.)

**Comment by opoudjis** [comment]
Citations are now more or less in a bibitem model; @ronaldtse, is there something else for this ticket?

**Comment by ronaldtse** [comment]
The BibItem model has been slightly refactored, if we can align implementation with it -- it would be great. We've also moved document metadata into BibItem so we can update that too.

**Comment by opoudjis** [comment]
@ronaldtse: done. If this ticket is now for an asciidoctor-biblio merger, I'll unassign myself :-)

**Comment by opoudjis** [comment]
This has been done, isobib gem
