### ISSUE TITLE
Migrate sass gem to sassc

### ISSUE THREAD

**Issue by opoudjis** [riboseinc/asciidoctor-iso#191]
The Sass maintainer is abandoning Ruby for Node (*spit*), and the gem will be shelved in March 2019.

http://sass.logdown.com/posts/7081811
https://github.com/sass/sassc-ruby#readme

**Comment by ronaldtse** [comment]
@opoudjis so the solution is to use `saasc` instead, which is acceptable for now...

**Comment by opoudjis** [comment]
Resolved in isodoc
