### ISSUE TITLE
Some abbreviations have shifted lines

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-iso#192]
As shown here:

![screen shot 2018-07-20 at 10 48 36 am](https://user-images.githubusercontent.com/11865/42980569-8215ac0e-8c0a-11e8-8ca7-e20f270e21bb.png)

**Comment by opoudjis** [comment]
This is a piece of CSS I keep fixing, and that keeps not staying fixed. OK, will get to it tonight.

**Comment by opoudjis** [comment]
I've just regenerated the HTML for iso-cantonese-romanization, and I cannot replicate this. This was fixed a couple of weeks ago, by putting the following in the stylesheet:
 
````
dd p, dt p {
margin-top: 0px;
}
````
Could you run Bundle update in the repository, and try again?

**Comment by ronaldtse** [comment]
Yes this is fixed. Thanks @opoudjis !
