### ISSUE TITLE
Square brackets in tables not rendered

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-iso#195]
I have a table like this, and the text within square brackets are not rendered in ISOXML.

```adoc
.My table
[cols="a,a,a",options="header"]
|===
|*Slash wrapping*
|*Angular brackets*
|*Square brackets*

|/_null_/
|<la>
| [ʔ]

|===
```

Becomes

```xml
<table id="_b7b15fa4-1569-49b0-9d84-34f4b0f81337">
  <name>My table</name>
  <thead>
    <tr>
      <th align="left">
        <strong>Slash wrapping</strong>
      </th>
      <th align="left">
        <strong>Angular brackets</strong>
      </th>
      <th align="left">
        <strong>Square brackets</strong>
      </th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td align="left">
        <p id="_57c3ed96-88df-49e5-86b9-778d709b22e4">/<em>null</em>/</p>
      </td>
      <td align="left">
        <p id="_a172723f-69c8-49d5-8477-1a8001802b05">&lt;la&gt;</p>
      </td>
      <td align="left"/>
    </tr>
  </tbody>
</table>
```

Notably, the text within the square brackets are gone.

**Comment by opoudjis** [comment]
that is likely an ASCIIdoc markup issue, since square brackets on their own are treated as ASCIIdoc macro markup. Try back slashing it.

**Comment by ronaldtse** [comment]
The corresponding Asciidoctor issue is this https://github.com/asciidoctor/asciidoctor/issues/2495 . Why this is the case goes beyond me. I have resolved to use `++[++blah]` to fix this issue now.

**Comment by ronaldtse** [comment]
(and in the tables, use `"1"` instead of `"a"` for the type of cell)
