### ISSUE TITLE
Text validation

### ISSUE THREAD

**Issue by opoudjis** [riboseinc/asciidoctor-iso#20]
I am issuing warnings for text content which may contravene ISO style:

* numbers with what looks like dots instead of commas for decimal points
* groups of numbers without spacing for every three digits
* no space before percent sign
* no bracketing of tolerance in percentage

**Comment by opoudjis** [comment]
Other checks introduced:

* No recommendations, permissions or requirements (by keyword) in: foreword, scope, introduction, term examples and examples, notes, footnotes.
* No subclauses that are the only child of a clause. (In clauses, annexes, or scopes.)
* Warning if there are 5 levels of subclause nesting. (Never actuated, Asciidoc only permits 4 levels of subsection.)
* Warning if non-ISO/IEC reference turns up as normative
* Warning if term definition starts with an article, or ends with a period.
* Warning if there is a title intro or title part in  only one of the two languages.

**Comment by ronaldtse** [comment]
Awesome thanks @opoudjis !
