### ISSUE TITLE
Refactor ISO XML document model

### ISSUE THREAD

**Issue by opoudjis** [riboseinc/asciidoctor-iso#23]
In line with the revised model generated by @ronaldtse . I'm presuming ISO XML is a subset of @ronaldtse's more general model.

**Comment by ronaldtse** [comment]
@opoudjis we want to make IsoStandardDocument (ISO XML) an "instance/implementation" of the StandardDocument model, so IsoStandardDocument should fully implement StandardDocument.

**Comment by opoudjis** [comment]
And because ISO will be more restrictive (e.g. imposes order on sections), the ISO XML schema would be a subclass of the Standard model (I used the wrong word with "subset"). 

So: the Standard model has:

````
sections: BasicSection[1..]
````

The ISO XML will have

````
sections: Sections

Sections = {
scope, norm_ref, terms_defs, symbols_abbrevs?, clause+, annex*, bibliography
}
````

And because all of those are BasicSections, the ISO XML schema will be considered to be an instance of the StandardDocument model. Right?

**Comment by opoudjis** [comment]
Will be doing these one element at a time.

**Comment by ronaldtse** [comment]
You’re right, the IsoDoc schema should be an instance of StandardDocument.

**Comment by opoudjis** [comment]
Put up discussion on https://github.com/riboseinc/isodoc/wiki/ISODoc-document-model-discussion ; will use that to discuss IsoDoc schema, to allow for easy threading.

**Comment by opoudjis** [comment]
https://github.com/riboseinc/isodoc/wiki/ISODoc:-Top-Level 

Refactored ISO model to align with this. 1 pending query: rename copyright_owner => copyright.

**Comment by opoudjis** [comment]
Done
