### ISSUE TITLE
Formatting of "Note X to entry" (Terms and definitions "NOTE:"), body content "NOTE" and "EXAMPLE"

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-iso#29]
The formatting of "Note X to entry" (Terms and definitions "NOTE:"), body content "NOTE" and "EXAMPLE" is currently in Times New Roman instead of the body font "Cambria".

The formatting of these elements should match the ISO template.

**Comment by opoudjis** [comment]
CSS error
