### ISSUE TITLE
Page breaks after Foreword, Introduction, Title, every Annex, and Bibliography

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-iso#30]
Page breaks should be automatically inserted after major sections (Level 1 sections).

They should also work in the case where the user wants to jump to the next page to make things look nicer.

**Comment by opoudjis** [comment]
> They should also work in the case where the user wants to jump to the next page to make things look nicer.

That means we add the page break command (Asciidoctor thematic break). Deferred to #24.

**Comment by opoudjis** [comment]
> Page breaks should be automatically inserted after major sections (Level 1 sections).

Following the template, that's not where the page breaks occur: They occur before: Foreword, Introduction, Title (before Scope), the first Annex (and presumably the other Annexes as well), and Bibliography.

**Comment by ronaldtse** [comment]
@opoudjis indeed:

Page-separated sections are: the Foreword, Introduction, Title, every Annex, and Bibliography.

**Comment by ronaldtse** [comment]
@opoudjis is this implemented? If so, could you tag the commit here (or use the commit message to indicate so it automatically tags)? Thanks!
