### ISSUE TITLE
Rice model Word document "Vache Equipment" should be left aligned but now "justified"

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-iso#35]
`Vache Equipment` is now spanning the entire row instead of being left aligned.

**Comment by opoudjis** [comment]
I was hoping you wouldn't notice. :-) Yes, address listings should not be justified, for that reason. The solution is to introduce left aligned vs justified into the isoxml document model, and that needs to be deferred to #24. (A lot of these will.)

**Comment by opoudjis** [comment]
Resolved with addition to document model of paragraph alignment.
