### ISSUE TITLE
AsciiISO => HTML should actually be AsciiISO => ISO XML => HTML

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-iso#38]
As title. Directly AsciiISO => HTML without using our backend will lose lots of ISO related data, such as title, parts, etc.

**Comment by ronaldtse** [comment]
As discussed in #40 we will have:

AsciiISO ==(asciidoctor-iso)=> IsoDoc ==(isodoc-html)=> HTML

**Comment by opoudjis** [comment]
This is in fact the existing workflow; what more needs to go into this ticket?

**Comment by ronaldtse** [comment]
I think it's all good now. Closing.
