### ISSUE TITLE
Expressing ISO/IEC JTC1/SC27 in document header attributes

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-iso#39]
Usually there is a TC number, but there are some JTCs like JTC1 is jointly run by "ISO" and "IEC".

How do we express these in the header? Like this?

```
:technical-committee-number: JTC1
:technical-committee: Information technology
:subcommittee-number: 27
:subcommittee: IT Security techniques
:workgroup-number: 1
:workgroup: Information security management systems
```

P.S. There are also
* "JWG[x]" (e.g. JWG8 of TC 154) that are "jointly" run with another party.
* "JMA[x]" as "joint maintenance agencies"
* These links gives you more varieties too: 
** https://www.iso.org/committee/45020.html
** https://www.iso.org/committee/54904.html
** https://www.iso.org/committee/48750.html
** https://www.iso.org/committee/45986.html
* See some "joint" WGs here: https://www.iso.org/committee/46706.html

**Comment by opoudjis** [comment]
The TC abbreviation in e.g. `ISO  TC 34/SC 4/WG 3` would need to change to the new abbreviation; e.g. `ISO/IEC JTC 1/SC 4/JWG 3`. That means that the initials `TC` are no longer supplied in the template: they need to be supplied in the document attribute (although `TC` can be supplied by default. I will also need to give an "agency" abbreviation, which would default to "ISO". So:

````
:agency: ISO/IEC
:technical-committee-number: JTC 1
:subcommittee-number: 27
:workgroup-number: JWG 1
````

would render as ISO/IEC JTC 1/SC 27/JWG 1

whereas 

````
:technical-committee-number: 1
:subcommittee-number: 27
:workgroup-number: 1
````

would render as ISO TC 1/SC 27/WG 1

Please confirm. Also, the prefix to the standard number itself would have to change to the agency prefix, if supplied.

**Comment by ronaldtse** [comment]
`agency` prefix is fine.

I think we should give these attributes to modify the prefix:
* `technical-committee-type`: `TC`, `PC`, `JTC`, `JPC`. Default `TC` if not supplied.
* `subcommittee-type`: `SC`, `JSC` (optional, there may not be an SC). Default `SC` if not supplied.
* `workgroup-type`: too many types to validate for `WG`, `JWG`, `JAG`, `AG` (advisory group), `AHG`, `SWG`, `SG`, `MA` (maintenance agency), `CORG`, `JCG`, `CAG`. Default `WG` if not supplied

* `technical-committee-number` mandatory
* `subcommittee-number` optional
* `workgroup-number` optional

**Comment by opoudjis** [comment]
The agency prefix should be substituted by bibitem/Publisher

**Comment by opoudjis** [comment]
Which means this ticket is now blocked by the model refactoring of including bibitem as document metadata.

**Comment by opoudjis** [comment]
Model changes: technical committees, subcommittees, and workgroups all have types added.

**Comment by opoudjis** [comment]
Tech committees, subcommittees, workgroups typed.
