### ISSUE TITLE
Derive Reference Number

### ISSUE THREAD

**Issue by opoudjis** [riboseinc/asciidoctor-iso#4]
Derive reference number  from ISO document number + Stage. Why does the Rice Model have "(E)"?

**Comment by ronaldtse** [comment]
E for English, F for French. ISO Standards must have E and F versions.

**Comment by opoudjis** [comment]
And that means there will need to be a French version of the template once I create it, right?

**Comment by ronaldtse** [comment]
I think we need to support a document that is in French. I’m not sure if we should support translations inherently (locale per phrase) or on a document level (locale per document). Maybe the latter is easiest.

**Comment by opoudjis** [comment]
If the reference number is derived from the ISO doc number, part number, year, and language, then it does not need to be included in the Asciidoc or the XML: the downstream tools can derive it.

**Comment by ronaldtse** [comment]
Yes, you are correct. Lest forget not the "Stage" abbreviation (e.g., "DIS", "WD", "CD", "NWIP", "FDIS", "IS"...). We just need to set the authoritative number for the downstream tools, right?

**Comment by opoudjis** [comment]
Stage abbreviation now added to frontispiece of spec and to document number
