### ISSUE TITLE
Separate isoxml2word as separate gem

### ISSUE THREAD

**Issue by opoudjis** [riboseinc/asciidoctor-iso#40]

**Comment by opoudjis** [comment]
@ronaldtse , you decide gem name and create repo, I will populate and create overarching script

**Comment by ronaldtse** [comment]
So 3 repos created:

* https://github.com/riboseinc/isotext (some other operations on isotext)
* https://github.com/riboseinc/isotext-html IsoText to HTML
* https://github.com/riboseinc/isotext-word IsoText to Word

**Comment by opoudjis** [comment]
Am now thinking they should be a single gem with multiple classes inheriting from common HTML (which should be as Microsoft-neutral as possible); will come to this once I've finished #47

**Comment by opoudjis** [comment]
Done to https://github.com/riboseinc/isodoc, and I'm not convinced the other two gems are needed at all, given the refactoring to html2doc
