### ISSUE TITLE
Add source and author to quote

### ISSUE THREAD

**Issue by opoudjis** [riboseinc/asciidoctor-iso#42]

**Comment by opoudjis** [comment]
Author is redundant to source; a citation for the quote is sufficient, and the author can be added in citeAs if not extracted from the bibliography, as a rendering choice.

**Comment by ronaldtse** [comment]
How about this -- a quotation is logically a citation with a different display text, so should quote just inherit from Citation but provide some content?

**Comment by opoudjis** [comment]
Yup: which amounts to quote = text + citation. The author attribute can still be supplied, but it is decorative only (like a citeAs), since the author can always be derived from the citation.

**Comment by opoudjis** [comment]
I'll still put the author in as an optional attribute, but it will be text only, and if it is absent, the gym will attempt to derive the author from the citation, if present.
