### ISSUE TITLE
XML: revisit element names

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-iso#45]
* `<iso-standard xmlns="http://riboseinc.com/isoxml">` => `<iso-standard-document xmlns="https://open.ribose.com/isoxml">`

Element names should be hyphenated rather than underscored, e.g.,:

* `<title_intro>, <title_main>`

This can be changed:

```xml
      <iso_ref_title id="ISO712">
        <isocode>712</isocode>
        <isotitle>Cereals and cereal products — Determination of moisture content — Reference method</isotitle>
      </iso_ref_title>
```

into this:
```xml
      <reference id="ISO712" type="iso">
        <document-code>712</document-code>
        <title>Cereals and cereal products — Determination of moisture content — Reference method</title>
        <date>2009</date>
      </reference>
```

This can be changed:

```xml
      <termdef id="paddy">
        <term>paddy</term>
        <admitted_term>paddy rice</admitted_term>
        <admitted_term>rough rice</admitted_term>
        <termdefinition>
          <p>rice retaining its husk after threshing</p>
        </termdefinition>
        <termref>
          <eref target="ISO7301" format="inline"/>
          <isosection> 3.1</isosection>
        </termref>
      </termdef>
```

Into this:

```
      <term-definition id="paddy">
        <term>paddy</term>
        <admitted-term>paddy rice</admitted-term>
        <admitted-term>rough rice</admitted-term>
        <definition>
          <p>rice retaining its husk after threshing</p>
        </definition>
        <term-reference>
          <eref target="ISO7301" format="inline"/>
          <clause>3.1</clause>
        </term-reference>
      </term-reference>
```

**Comment by opoudjis** [comment]
Will do this as cleanup operation, will keep underscores in internal Nokogiri builder code.

**Comment by opoudjis** [comment]
@ronaldtse Please review https://github.com/riboseinc/asciidoctor-iso/blob/master/lib/asciidoctor/iso/isoxml/validate.rnc for any run-in element names that you think should be hyphenated; e.g. "projectnumber".

**Comment by ronaldtse** [comment]
* documentnumber
* tc-documentnumber
* termdomain, termnote, termsource, termexample
* imagetype
* "safety precautions" => "safety_precautions" ?
* docidentifier,  publishdate, accesseddate, creationdate
* biblioNote => bib-note
* partOf => part-of

**Comment by opoudjis** [comment]
Noting that in the RNC and RNG spec, dashes are not allowed (they are used to indicate exception classes instead); but jing-trang and jing, the RNG tools we use, have no problem with dashes.

**Comment by opoudjis** [comment]
In addition now, xpath queries in Nokogiri break with hyphenated element names: `//hyphenated-name` works, but `//name[hyphenated-name]` does not. Xpath testbeds online allow it, so this is a Nokogiri Xpath issue; I already had to do a workaround to put hyphens into element names by postprocessing, because the Nokogiri builder does not accept them either.

The spec may allow hyphenated names, but it's very clear that tools have problems with it—enough tools that making elements hyphenated is going to compromise other people's ability to use the schema. @ronaldtse: Please let me put underscores back in.

**Comment by ronaldtse** [comment]
Alright, perhaps we just use a run-in type of name `unhyphenatedname`? 

http://tdg.docbook.org/tdg/5.1/bibliography.html

**Comment by opoudjis** [comment]
... You'd prefer `unhyphenatedname` over `unhyphenated_name`? I can do that, I'm just surprised.

**Comment by opoudjis** [comment]
Agreeing to keep them run-in; I will stop any further conversion of element names. I will not undo any element names that are already hyphenated, unless the need comes up.
