### ISSUE TITLE
Support multi-paragraph footnotes

### ISSUE THREAD

**Issue by opoudjis** [riboseinc/asciidoctor-iso#49]
Asciidoctor natively accepts only one-line footnotes, because it uses an inline formatting macro. Implementing multiple paragraph footnotes would require an Anchor model, just as is being projected for reviewer comments.

**Comment by opoudjis** [comment]
http://discuss.asciidoctor.org/footnotes-with-paragraph-breaks-td4130.html

Asciidoctor excludes them by design, with a stupendously short-sighted view of document structure. (Asciidoctor is an authoring system, not a style nanny.) The ISOXML syntax already permits multi-para footnotes, and the isodoc renderer more or less deals with them. We just don't have a way of getting multi-para footnotes into ISOXML using Asciidoc; and while I could make up custom blocks to do it, I'm not eager to break Asciidoc to do it. @ronaldtse, you ok if I drop this ticket, since it ends up being Asciidoc-specific?

**Comment by ronaldtse** [comment]
Yeah we can drop this then. Can you add a note to README to indicate that this is an Asciidoctor caveat?
