### ISSUE TITLE
Make term definition optional

### ISSUE THREAD

**Issue by opoudjis** [riboseinc/asciidoctor-iso#54]

**Comment by opoudjis** [comment]
I'm doing this in the grammar, but with some unease, @ronaldtse. Can I confirm you still want this?

**Comment by ronaldtse** [comment]
The original reason I wanted this is when creating a draft we didn't define the definitions yet, and the result is the file couldn't compile. In "real" this shouldn't happen -- is there a way to just "WARN" instead of block compilation?

**Comment by opoudjis** [comment]
Actually the file does compile even if it is ungrammatical. Often the code assumes mandatory elements are there, by using .at instead of .xpath. but that is a bug of defensive coding, and I had fixed that bug. So I will make it mandatory again.

**Comment by ronaldtse** [comment]
Thank you @opoudjis !

**Comment by opoudjis** [comment]
Done
