### ISSUE TITLE
Annex should contain clauses not subsections?

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-iso#58]

**Comment by opoudjis** [comment]
If they should, then that applies to clause as well. I'd rather we keep it as subsections, just in case that is ISO specific.

**Comment by opoudjis** [comment]
@ronaldtse as you know, I dislike renaming elements, because it gets in the way of code reuse. Would rather we keep the subsections generic.

**Comment by ronaldtse** [comment]
I think we need some more discussion about this -- there is a difference of an Annex vs Appendix in an ISO Standard (see ISO Directives Part 1 which contains both).

ISO Standards specifically require Annexes to contain clauses. This does make sense for any standard because it allows an annex clause to be actually referred to. That said, ISO Standards permit hanging paragraphs in Annexes which are not ideal.

Thoughts?

**Comment by opoudjis** [comment]
Rename: 

* clause/subsection to clause/clause
* terms/terms to clause/terms
* references/references to clause/references

**Comment by opoudjis** [comment]
I remain nervous about renaming subsections to clauses

Looking at standoc, you have StandrdHierarchicalSection/subsection, ClauseSection/subsection, AnnexSection/subsection

the fact that these are clauses rather than subsections in Iso standards is specific to ISO, it is not general to Standoc

Therefore I don't believe they should be renamed in ISOXML

**Comment by opoudjis** [comment]
Have changes all terms/terms to clause/terms, references/references to clause/references

**Comment by opoudjis** [comment]
Renamed all subsections to subclauses in all grammars.

**Comment by opoudjis** [comment]
Renaming all subclauses to clauses. Have added preface and bibliography containers.
