### ISSUE TITLE
Creator should be creators. The TC stuff is iso specific.

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-iso#59]
We can add editors, drafters, authors even if they are not displayed (they are in some NB standards).

Model this in isodoc-models.

**Comment by opoudjis** [comment]
The TC stuff is coming out of the generic model, and going back in to the ISO specific model.

The plural/singular in the UML, I have ignored anyway in the grammar for attributes: I have only used singulars, since they end up as repeating elements.

**Comment by ronaldtse** [comment]
For plural/singular, should we do this instead?

```xml
<creators>
  <creator> ... </creator>
</creators>
```

**Comment by opoudjis** [comment]
It is common XML practice to have a creatorList or creators containing creator, yes, and to have a container for one or more repeating instances of an element. It's not universally accepted; see https://stackoverflow.com/questions/1156051/use-a-parent-xml-element-as-a-container-for-reoccurring-child-elements, https://www.ibm.com/developerworks/library/x-contain/index.html — it is considered bound up with XS Schema and structs in programming languages, and we aren't really bound by either. (And it will make the Xpaths even longer.)

So it's common, but not mandatory, and I don't think it's needed.

**Comment by ronaldtse** [comment]
OK let's keep it simple!
