### ISSUE TITLE
Update BibliographicItem model (and migrate from StandardDocument)

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-iso#61]
Reflect changes in https://github.com/riboseinc/isodoc-models/issues/15

Moved from StandardDocument to BibItem:

* CopyrightAssociation moved to BibItem
* DocumentStatus
* DocumentType
* DocumentIdentifier
* TitleInfo
* Author

BibItem refactored:
* Person / Organization inherit from Contributor
* Publisher information described in ContributorRole
* Added LocalizedString definition to allow for multiple languages in title (from StandardDocument)
* ParagraphBlocks changed to FormattedString which allows rich text

**Comment by opoudjis** [comment]
Ticket encompasses all updates to Isodoc models up to 2017-02-07.

**Comment by opoudjis** [comment]
Started. @ronaldtse , this is going to take several days; PLEASE do not touch the grammars until this task is done, there is a lot for me to keep track of.

Starting with toplevel element and bibliography.

**Comment by opoudjis** [comment]
There will be feedback to the doc model at the end; I am implementing a grammar with changes I want to see, and I will discuss those changes with @ronaldtse, possibly reverting them if he talks me out of it.

**Comment by opoudjis** [comment]
So far: populated and properly rendering bibdata, replacing the list of initial metadata. I have not added in any authoring or other dates under bibdata.

**Comment by opoudjis** [comment]
Reordered sections. Note that Normative References now appear at the end of the XML, though they are still rendered by isodoc in the right place.

**Comment by opoudjis** [comment]
All changes done to asciidoctor-iso and isodoc. To do:

* asciidoctor-csd
* asciidoctor-gb
* Changes from debate with @ronaldtse at https://github.com/riboseinc/isodoc-models/issues/15

**Comment by opoudjis** [comment]
Folded all changes into CSD, GB, and so pushing updates.

**Comment by opoudjis** [comment]
All work done.
