### ISSUE TITLE
TOC is normally 2 levels, but for Annexes only 1 level

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-iso#67]
TOC for Annexes don't show subsection numbers (i.e. only 1 level).

See Rice document TOC.

**Comment by opoudjis** [comment]
.... I can't replicate this. The current TOC, when I update it, is:

````
Annex A (Normative)  Determination of defects	8
A.1. Principle	8
A.2. Apparatus	8
A.3. Sampling	8
A.4. Procedure	8
A.5. Determination	9
A.6. Calculation	9
A.7. Test report	10
Annex B (Informative)  Determination of the waxy rice content of parboiled rice	11
B.1. Principle	11
B.2. Apparatus	11
B.3. Reagents	11
B.4. Sampling	11
B.5. Determination	11
B.6. Calculation	12
B.7. Test report	12
````

... Those are Level 2; the headings don't repeat "Annex", because they are taken from the headings, which do not repeat it.

What am I missing?

**Comment by ronaldtse** [comment]
Aha, the B.X should not appear. Just Annex B.

**Comment by opoudjis** [comment]
So you *don't* want Level 2 to show in annexes, but you do in the main body.

That means I have to style Annexes h2 in Word in a different style, so they don't get picked up by the indexer.
