### ISSUE TITLE
Figures have preambles and postambles

### ISSUE THREAD

**Issue by opoudjis** [riboseinc/asciidoctor-iso#69]
Refer ISO/IEC Part 2

**Comment by opoudjis** [comment]
Not the way I read the spec. The business about the units in the diagram I believe are words meant to be included in the diagram. Any additional information at the bottom of the diagram is formally defined --- notes, definitions, footnotes, source (which I'm not enthusiastic about including), and already catered for. I'm not seeing an indication of figures having free text preambles and postambles.

@ronaldtse, you indicated that figures have  preambles and postambles; what do you base that on?

**Comment by ronaldtse** [comment]
Right, we don't need this since the post-figure content is well defined. But in the case of RFCs they allow post/preambles on figures. Should we support this in StandardDocument or should that be a profile for RFCs?

**Comment by ronaldtse** [comment]
(probably the latter)

**Comment by opoudjis** [comment]
Agree, I think it's the latter. It's always easier for inheritance to add than to subtract.
