### ISSUE TITLE
Warning on ISO document reference considered non-ISO/IEC

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-iso#76]
```
asciidoctor: WARNING(Section: Normative References): non-ISO/IEC reference not expected as normative: <ref id="ISOGuide73">[ISO Guide 73:2009]</ref>, <em>Risk management&#8201;&#8212;&#8201;Vocabulary</em>
```

There are other documents that can be referenced as normative; these include the JTC1 AROs (search for "ARO" in https://www.iso.org/isoiec-jtc-1.html).

Maybe if anything that starts with "ISO" or "IEC" doesn't need a warning?

**Comment by opoudjis** [comment]
Regex is now `(ISO|IEC)[^0-9]*` for the prefix, followed by the code; that will catch ISO Guide or IEC or ISO/IEC.

**Comment by opoudjis** [comment]
But the new prefixes are not being stored as crossreferences: need to fix.
