### ISSUE TITLE
Differentiate annexes into normative and informative?

### ISSUE THREAD

**Issue by opoudjis** [riboseinc/asciidoctor-iso#8]
It's not part of Asciidoc structure, but we can parse the `(normative)`, `(informative)` in annex titles, and differentiate in the XML output between`<informative_annex>` and `<normative_annex>`, or `<annex type="normative">` and `<annex type="informative">`. But is this useful downstream?

**Comment by ronaldtse** [comment]
I think I believe this is necessary, we could either go with:

* the `(normative)` part in the title
* or use a specifier like `[annex,normative]` to assign the block to be an annex

It should result in a `<section type=annex>` element. Not sure if the "annex_type" is important downstream, but if we could do `<section type=annex subtype=normative>` it could work better for rendering tools.

**Comment by opoudjis** [comment]
I currently call them `<annex>`, and the sections of the main text `<clause>`; in the document model, they are identical. I will call them `<section type="annex">` and `<section type="clause">` unless you tell me otherwise. I will introduce `subtype`, but note that this only applies to annexes, not clauses.

**Comment by opoudjis** [comment]
... I'm keeping them as annex and clause for now, but I have introduced the subtype and the corresponding markup.
