### ISSUE TITLE
External references/No terms on Terms & Definitions

### ISSUE THREAD

**Issue by opoudjis** [riboseinc/asciidoctor-iso#82]
ISO/IEC DIR 2 p. 47-48:

1. Allow reference to external document's terms & definitions:

````
[doc=iso3339]
== Terms and Definitions
````

````
<terms>
<externaldoc>iso3339</externaldoc>
....
````

2. Allow the terms and definitions section to be empty:

````
== Terms and Definitions
{contains no subclauses}
````

````
<terms>
<noterm/>
</term>
````

This can be combined with external document term.

3. Ignore the boilerplate supplied in the Asciidoc, populate the boilerplate (with reference to external documents or empty terms) in isodoc.

**Comment by ronaldtse** [comment]
Just to clarify the effect of this will be the rendering of a boilerplate text like this?

```
For the purposes of this document, the terms and definitions given in ISO/IEC 27000 and the following apply.
ISO and IEC maintain terminological databases for use in standardization at the following addresses:
*	ISO Online browsing platform: available at http://www.iso.org/obp
*	IEC Electropedia: available at http://www.electropedia.org
```

(where ISO/IEC 27001 is supplied as a T&D source, and ISO/IEC 27001 is supplied in normative references)

**Comment by opoudjis** [comment]
That's right, and any boilerplate in the source asciidoc will be ignored.

**Comment by ronaldtse** [comment]
OK. And we shall have the same thing for asciidoctor-gb too?

It will be:
```
<<ISO27000, ISO/IEC 27000>> 中确立的以及下列术语和定义适用于本标准。
```

**Comment by opoudjis** [comment]
Yes. I'll be asking for boilerplate, but thank you!

**Comment by ronaldtse** [comment]
^-- that's the boilerplate above, in case I forget 😉
