### ISSUE TITLE
Symbols and Abbreviated Terms subclause

### ISSUE THREAD

**Issue by opoudjis** [riboseinc/asciidoctor-iso#83]
Permit Symbols and Abbreviated Terms to be a subclause of Terms and Definitions (if renamed Terms, Definitions, Symbols and Abbreviated Terms). ISO/IEC DIR 2, p. 52.

**Comment by ronaldtse** [comment]
Agree -- FYI the title "Terms, Definitions, Symbols and Abbreviated Terms" is simply for demonstration and can be manually altered:

> The symbols need not be numbered. For convenience, the symbols and abbreviated terms may be combined with the terms and definitions in order to bring together terms and their definitions, symbols and abbreviated terms under an appropriate composite title, **for example** “Terms, definitions, symbols and abbreviated terms”.

**Comment by ronaldtse** [comment]
And for the record, GB also allows the combining of these sections.

**Comment by opoudjis** [comment]
The title is indeed illustrative, but the approach of this gem has been to use fixed titles.

**Comment by opoudjis** [comment]
Take the opportunity to confirm that  "Terms, Definitions, Symbols and Abbreviated Terms" is in fact generated.

**Comment by ronaldtse** [comment]
It is merely an example given; it is not generated.
