### ISSUE TITLE
Title validation

### ISSUE THREAD

**Issue by opoudjis** [riboseinc/asciidoctor-iso#85]
ISO/IEC DIR 2 p. 63

1. Each first level subclause should have a title
2. If one subclause has a title, all its siblings should have a title

**Comment by ronaldtse** [comment]
And is this destined for isodoc validation instead of asciidoctor-iso?

**Comment by opoudjis** [comment]
All validation occurs in asciidoctor-iso, because it is against the schema, not the HTML output.

**Comment by ronaldtse** [comment]
But when we finally refactor isodoc, the isodoc schema should be validated in isodoc rather than asciidoctor-iso right? This is because we will have other textual formats render into isodoc.

**Comment by opoudjis** [comment]
Depends. Most of this is done on the ISOXML output of asciidoctor-iso, before it hits isodoc. It could done on the input of isodoc instead, but I'd want to defer any such refactoring.

**Comment by ronaldtse** [comment]
It would definitely be better when asciidoctor-iso calls `isodoc.validate_node(node)` / `isodoc_node.validate` (or `isodoc_document.validate`) to catch validation errors.
