### ISSUE TITLE
Note numbering

### ISSUE THREAD

**Issue by opoudjis** [riboseinc/asciidoctor-iso#86]
Outside of termnotes, all notes shall be numbered, but only if there is more than one in their container.

**Comment by opoudjis** [comment]
Move to isodoc

**Comment by ronaldtse** [comment]
@opoudjis could you help refer to the specific isodoc issue for reference purposes? Thanks!

**Comment by opoudjis** [comment]
https://github.com/riboseinc/isodoc/issues/25
