### ISSUE TITLE
Generate Word output

### ISSUE THREAD

**Issue by opoudjis** [riboseinc/asciidoctor-iso#9]
For pasting into ISO Word template, or at least to generate a Word document for ISO consumption. Default pathway would be ISO XML to DocBook via XSLT.

1. AsciiDoc -> ISO-XML (the format we're doing) -> Docbook -> Word

**Comment by ronaldtse** [comment]
Agree with the path!

**Comment by opoudjis** [comment]
Pathway is now AsciiDoc -> ISO-XML -> Word HTML -> Word.

**Comment by opoudjis** [comment]
Will close this ticket once have collated Word output for Rice document with the PDF, and gone through ISO/IEC Part 2 again (particularly for inserting boilerplate).

**Comment by opoudjis** [comment]
Ticket will be closed once I've created tickets out of collating output with ISO/IEC Part 2.

**Comment by opoudjis** [comment]
Have gone though ISO/IEC DIR 2 again, will add tickets from there.
