### ISSUE TITLE
Update according to isodoc-model updates

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-iso#92]
Update implementation according to changes in isodoc-models:
https://github.com/riboseinc/isodoc-models/commit/e5b92981dbed3bc8c54154c3e5060cce6473289a

The specific changes are:

* extraction of docRelations from StandardDocument to BibliographicItem, DocumentRelations now specify more relationship types
* BibliographicItem attributes now takes `LocalizedString` instead of `FormattedString`
* BibItemLocality (part of the Citation model) now has `reference` split into `referenceFrom` and `referenceTo` to allow citation of a range, e.g., Section 1.1 to 1.9.

The rest of the models are unchanged -- only diagrams split up for ease of understanding.

**Comment by opoudjis** [comment]
I disagree about change from FormattedString to LocalizedString. Bibliographic strings can have formatting; e.g. subcripts, italics for mentions of titles.

**Comment by opoudjis** [comment]
Other changes made

**Comment by ronaldtse** [comment]
@opoudjis you're right -- I got confused. Fixed now, all FormattedString's in BibItem.

**Comment by ronaldtse** [comment]
Close this then?

**Comment by opoudjis** [comment]
Yup. I also have added referenceTo to isodoc, asciidoctor-iso, asciidoctor-gb.
