### ISSUE TITLE
Create document template repo for quick start

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-iso#94]
We should put the rice document (split into different sections) with a proper README and a Travis script as a quick start template.

**Comment by opoudjis** [comment]
Doing this in https://github.com/riboseinc/isodoc-rice/

You'll need to say more about what you mean by "a proper README and a Travis script". There are several instances of documentation of AsciiISO already, including https://github.com/riboseinc/asciidoctor-iso/wiki/Quickstart-Guide; I see no reason not to reuse that.

**Comment by opoudjis** [comment]
Created sections for isodoc-rice in https://github.com/riboseinc/isodoc-rice/issues

**Comment by opoudjis** [comment]
This issue remains in limbo, @ronaldtse; the split up document will no doubt end up in a Metanorma website, but I still need more information from you about what you'd want to see in a README, and what a Travis script would do.

**Comment by ronaldtse** [comment]
@opoudjis sorry for the delay.

README: should contain (1) how to build the document, and (2) a simple walkthrough of the document sections.

Travis script: build the document (i.e. run `bundle exec metanorma -t iso rice.adoc`) and ensure that it returns success, so we can catch when document building fails. Just like what we have in https://github.com/riboseinc/rfc-asciirfc-minimal/blob/master/.travis.yml

**Comment by opoudjis** [comment]
That, I can do. Back to bug.

**Comment by opoudjis** [comment]
Done

**Comment by opoudjis** [comment]
I'm not using metanorma to generate the files, because I want the repository to showcase the .xml output; metanorma suppresses outputting the ISO XML to disk.

**Comment by ronaldtse** [comment]
Oh, @opoudjis , in this case, can we have a command flag that allows outputting Metanorma XML to disk?

**Comment by opoudjis** [comment]
OK
